name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v7
      - name: rustfmt
        run: cargo fmt -- --check
      - name: clippy
        run: cargo clippy
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
